version: '3.8'

services:
  monitor-app:
    build: ./app
    container_name: meu-monitor
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app          
    depends_on:
      - web-alvo
      - db-alvo
    environment:
      - TZ=America/Sao_Paulo    
      - PYTHONUNBUFFERED=1      

  web-alvo:
    image: nginx:alpine
    container_name: web-server-teste
    ports:
      - "8080:80"

  db-alvo:
    image: postgres:13
    container_name: db-server-teste
    environment:
      # MUDAMOS AS CREDENCIAIS AQUI PARA FORÃ‡AR O RESET
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: senha_nova_123
      POSTGRES_DB: monitor_db

  smtp-alvo:
    image: mailhog/mailhog
    container_name: smtp-server-teste
    ports:
      - "1025:1025"
      - "8025:8025"