version: '3.8'

services:
  # 1. PROGRAMA PYTHON
  monitor-app:
    build: ./app
    container_name: meu-monitor
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app          
    depends_on:
      - web-alvo
      - db-alvo
    environment:
      - TZ=America/Sao_Paulo    
      - PYTHONUNBUFFERED=1      

  # 2. WEB (Nginx)
  web-alvo:
    image: nginx:alpine
    container_name: web-server-teste
    ports:
      - "8080:80"

  # 3. BANCO DE DADOS (Postgres)
  db-alvo:
    image: postgres:13
    container_name: db-server-teste
    environment:
      POSTGRES_PASSWORD: senha_secreta
      POSTGRES_DB: banco_teste

  # 4. SMTP (MailHog)
  smtp-alvo:
    image: mailhog/mailhog
    container_name: smtp-server-teste
    ports:
      - "1025:1025"
      - "8025:8025"